all: auto constexpr forloops lambda variadic

auto: auto.cpp
	g++ -o auto auto.cpp -std=c++11

constexpr: constexpr.cpp
	g++ -o constexpr constexpr.cpp -std=c++11

forloops: forloops.cpp
	g++ -o forloops forloops.cpp -std=c++11

lambda: lambda.cpp
	g++ -o lambda lambda.cpp -std=c++11

variadic: variadic.cpp
	g++ -o variadic variadic.cpp -std=c++11

clean:
	rm -f auto constexpr forloops lambda variadic
