all:
	g++ -o if_statements if_statements.cpp
	g++ -o loops loops.cpp
	g++ -o bool bool.cpp
	g++ -o simple_arrays simple_arrays.c
	g++ -o debugging debugging.cpp -g

clean:
	rm if_statements loops bool simple_arrays debugging
